### ISSUE TITLE
Changing namespace to CCCoreLib

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CCCoreLib#10]
**Describe the feature you would like**

The namespace is currently `CCLib`. Since the library was renamed when it was pulled out of CloudCompare, this should be changed to `CCCoreLib`.

**Comment by tmontaigu** [comment]
I'm proposing this without strong feeling/conviction: 

```C++
namespace CloudCompare {
    namespace CoreLib {
        int square(int num) {
            return num * num;
        }
    }
}

// if we were using c++17
namespace CloudCompare::CoreLib {
    int square(int num) {
        return num * num;
    }
}


// Users would do
namespace CCCoreLib = CloudCompare::CoreLib; // Or whatever pleases them


int main(void) {
    return CCCoreLib::square(2);
}
```

**Comment by asmaloney** [comment]
Thanks @tmontaigu - this is an intriguing idea I hadn't considered.

In trying to think of the +/-:

(+) It makes it explicit that CC == CloudCompare
(-) We would have to "renamspace" in quite a few places - wherever we include anything from CCCoreLib I think?
(-) It's nice when the namespace is the same as the lib name (CCCoreLib) out of the box (and it's a little more succinct) so there's less indirection

(+/-) Anything else?

So I'd lean slightly away from the extra namespace because it would require more changes to CloudCompare. If it's just the one name (CCCoreLib) I can mostly do an intelligent search/replace.

But overall I don't have strong feelings either way either :-)

**Comment by dgirardeau** [comment]
I don't like too long namespaces personally. And if we were to take the 'CloudCompare::Core::' option, I bet we would have to do the same for all the libraries eventually.

**Comment by tmontaigu** [comment]
Yes, apart from being explicit with the long namespace & creating a cloudcompare namespace where we independent libs could live it has no other real advantages and has the big drawback of being long to type which is annoying and the `namespace x = y;` only solve that to a point since we would need to repeat that everytime we include a CCCoreLib thing
