### ISSUE TITLE
How to load a .pcd point cloud?

### ISSUE THREAD

**Issue by funzoey** [CloudCompare/CCCoreLib#109]
Thanks for this amazing work!!
I'm new to C++ projects and very new to CCCoreLib or pcl, sorry for my fool issue. 
I just want to know How to load a .pcd point cloud and Where can I learn how to use CCCorelLib

**Comment by dgirardeau** [comment]
Hi,

CCCoreLib doesn't handle files loading or saving. This is done either with the qCC_io library of the CloudCompare project, or with specific plugins.

For the specific case of PCD files, this is done with the PCL plugin (based on the PCL library):
https://github.com/CloudCompare/CloudCompare/tree/master/plugins/core/Standard/qPCL/PclIO
