### ISSUE TITLE
Update header guards

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CCCoreLib#11]
**Describe the feature you would like**

Current header guards look like this:

```cpp
#ifndef AUTO_SEGMENTATION_TOOLS_HEADER
```

We should update these to include CCCORELIB to help avoid collisions.

```cpp
#ifndef CCCORELIB_AUTO_SEGMENTATION_TOOLS_HEADER
```

**Comment by dgirardeau** [comment]
Or switch to the simpler "#pragma once" ?

**Comment by asmaloney** [comment]
If all our platforms/compilers support it that would be good. I'll take a look at compiler support for it.

**Comment by asmaloney** [comment]
Looks non-standard, but supported on anything we care about (according to wikipedia):

https://en.wikipedia.org/wiki/Pragma_once
