### ISSUE TITLE
Remove Qt dependency

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CCCoreLib#18]
**Describe the feature you would like**

It would be great to get rid of the dependence on Qt. (We [attempted](https://github.com/CloudCompare/CloudCompare/pull/722) this a couple of years ago and made partial progress.)

#16 will get rid of one use (QAtomicInt).

The remaining cases are 3 uses of [QtConcurrent::blockingMap](https://doc.qt.io/qt-5/qtconcurrentmap.html) - two in DgmOctree and one in DistanceComputationTools.

Ideally we could do this using standard library methods - C++11 provides some [thread support](https://en.cppreference.com/w/cpp/thread). Maybe [std::async](https://en.cppreference.com/w/cpp/thread/async)?

If that is not sufficient, the use-case _should_ be straightforward to implement using [std::thread](https://en.cppreference.com/w/cpp/thread/thread).

Other options that would be lighter weight than Qt: [OpenMP](https://www.openmp.org/resources/refguides/) or [Threading Building Blocks
](https://en.wikipedia.org/wiki/Threading_Building_Blocks).

**Comment by andreadotti** [comment]
Hello, as a test I have successfully replaced QtConcurrent with `tbb::paralell_for` for the case of `DgmOctree` (and I believe the same strategy could be used in `DistanceComputationTools`).
However, as you can read in this link https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/72 TBB strongly discourages setting the number of threads explicitly.  The functionality for that is deprecated and will be removed soon.
As a consequence, using TBB, it will not be possible to set the number of threads anymore as in e.g. https://github.com/CloudCompare/CCCoreLib/blob/362c63a37241b43f0878ab5565661d38c8319aa8/src/DgmOctree.cpp#L3510

Considering this limitation, are you still willing to consider a PR or would you prefer, instead to maintain the possibility to set the number of threads and thus use OpenMP?

**Comment by dgirardeau** [comment]
Well, I'm not particularly against this idea, especially since using TBB remains optional?

**Comment by andreadotti** [comment]
Yes indeed, its use would be controlled by the existing cmake switch: `CCCORELIB_USE_TBB`.

**Comment by andreadotti** [comment]
Thank you for your feedback.
I have proposed a PR for your evaluation:
https://github.com/CloudCompare/CCCoreLib/pull/61

**Comment by andreadotti** [comment]
I think this can be closed, right? the PR has been merged. Thank you
