### ISSUE TITLE
Replace ZERO_TOLERANCE

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CCCoreLib#19]
**Describe the feature you would like**

We had discussed replacing [ZERO_TOLERANCE](https://github.com/CloudCompare/CloudCompare/issues/599) with the old `FLT_EPSILON`.

Maybe what we should provide here is inline methods instead. ZERO_TOLERANCE is mostly used for comparison - "is this less than zero-ish?" or "is this greater than zero-ish?"

This would make it a bit more readable and eliminate casting issues and warnings.

```cpp
if (range < CCLib::ZERO_TOLERANCE)
```
becomes:

```cpp
if ( CCLib::lessThanEpsilon( range ) )
```

This might be implemented like this:
```cpp
inline bool	lessThanEpsilon( double x )
{
   return x < std::numeric_limits<double>::epsilon();
}

inline bool	lessThanEpsilon( float x )
{
   return x < std::numeric_limits<float>::epsilon();
}
```

**Comment by dgirardeau** [comment]
Ok, then simply a template version?

template <typename T> inline bool	lessThanEpsilon( T x )
{
   return x < std::numeric_limits<T>::epsilon();
}

**Comment by asmaloney** [comment]
I considered that, but wanted to avoid templates as much as possible. I think it's overkill for this. Just causes longer compile times for no real return.

**Comment by asmaloney** [comment]
This was rolled into the plan for #20
