### ISSUE TITLE
Eigen vs. Jacobi?

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CCCoreLib#31]
I just noticed a code path that is not compiled and tested.

In _Neighbourhood.cpp_ there is code to use the Eigen library. This is controlled by `USE_EIGEN` which has to be defined manually in the code.

Should this be a cmake option so it's more obvious and easier to use?

If not - should this code be removed?

**Comment by dgirardeau** [comment]
Oh it was probably for a test (to compare the results). But I don't really want to add a new dependency to CCLib (as I already want to remove Qt).

**Comment by asmaloney** [comment]
OK - I'll remove it. 👍🏻
