### ISSUE TITLE
query on rotation matrix

### ISSUE THREAD

**Issue by vishnukumarts** [CloudCompare/CCCoreLib#32]
It's not about a bug,
On File RegistrationTools.cpp, RegistrationProcedure(),
I am seeing Rotation matrix is identified twice for the three-point case,

    Using quaternion
    followed by an arbitrary rotation.

I doubt why we need to do both or only quaternion is fine enough.

**Comment by dgirardeau** [comment]
No, both are necessary. The quaternion-based rotation aligns the two planes (see line 934), and then we use a second rotation to align the 3 points inside this plane (see how the first rotation is multiplied by the second one on line 995).
