### ISSUE TITLE
Propagating #defines

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CCCoreLib#5]
**Describe the bug**

We should be using CCCoreLib-specific names for any #define we are propagating to the including application. Otherwise we can conflict with existing defines.

Proposed:
| Old | New |
|---|---|
| USE_QT | CC_CORE_LIB_USES_QT |
| USE_CGAL_LIB | CC_CORE_LIB_USES_CGAL_LIB |
| USE_TBB | CC_CORE_LIB_USES_TBB |
| SCALAR_TYPE_DOUBLE | CC_CORE_LIB_USES_DOUBLE |
| SCALAR_TYPE_FLOAT | CC_CORE_LIB_USES_FLOAT |

(Updated based on feedback.)

**Comment by dgirardeau** [comment]
or CC_CORE_LIB for the sake of readability

**Comment by asmaloney** [comment]
That's good - I updated the table.
