### ISSUE TITLE
You have called ADD_LIBRARY for library CCAppCommon without any source files

### ISSUE THREAD

**Issue by guochaodlnu** [CloudCompare/CCCoreLib#50]
**Describe the bug**

**How to reproduce**

**Expected behaviour**

**Additional context**

**Your environment**
 - CCCoreLib Version (or git hash/tag):
 - OS & Version:
 - Qt Version (if compiling w/Qt):

You have called ADD_LIBRARY for library CCAppCommon without any source files. This typically indicates a problem with your CMakeLists.txt file

**Comment by guochaodlnu** [comment]
You have called ADD_LIBRARY for library CCAppCommon without any source files. This typically indicates a problem with your CMakeLists.txt file

**Comment by dgirardeau** [comment]
I don't have this problem on my side. Did you pull all the files (and submodules)?

**Comment by dgirardeau** [comment]
I can't reproduce this problem/warning. Are you sure you try to compile the library from the right path? (CCCoreLib root folder).

Because CCAppCommon is part of CloudCompare main repository, and not from CCCoreLib.
