### ISSUE TITLE
Noise Filter Neighbourhood Size

### ISSUE THREAD

**Issue by seiband** [CloudCompare/CCCoreLib#58]
When using the noise filter on point clouds there is a strange behaviour. Although setting it to KNN and using only 6 points it takes **much** longer than the SOR filter. It seems like the KNN methods depends on the kernel size and the other way around.

Within the code of the noise filter in CloudSamplingTools.cpp I found these lines:
```
	if (useKnn)
		octreeLevel = octree->findBestLevelForAGivenNeighbourhoodSizeExtraction(kernelRadius);
	else
		octreeLevel = octree->findBestLevelForAGivenPopulationPerCell(knn);
```
Shouldn't this be the other way around?

**How to reproduce**
1. Select a cloud
2. Go to 'Clean\Noise filter'
3. Click on 'Radius (Sphere)'
3. Input '6' as the kernel size
4. Select 'Points (kNN)'
5. Input '6' as the number of neighbours
6. Start filter

**Expected behaviour**

The processing shouldn't take much longer than the SOR filter. In my case for 20.000 points it almost took 10 seconds compared to the SOR filter (less than 1 second).

**Your environment**
 - CCCoreLib Version: 2.11.1
 - OS & Version: Windows 10
 - Qt Version: QT 5.15

**Comment by dgirardeau** [comment]
Nice catch! This is clearly a mistake.

6ef377fc7e87f9b17f28ef4c58eb37295c2d8113 should fix this!

**Comment by dgirardeau** [comment]
The 2.12.alha version online is now updated!
