### ISSUE TITLE
Licensing clarification request

### ISSUE THREAD

**Issue by andreadotti** [CloudCompare/CCCoreLib#60]
Hello,

I have noticed the remark regarding licensing in the [README](https://github.com/CloudCompare/CCCoreLib#license-special-note). I have also noticed that, differently from what mentioned there, the only file marked as _GPL_ instead of _LGPL_ is `./include/RayAndBox.h`

I am very interested in this project, but I would like to understand if there is an update on the licensing issue.

Thank you

**Comment by dgirardeau** [comment]
Ah, that's definitely a mistake! These license headers have been changed in a batch, and since most of the files of the CloudCompare project are GPL, I guess this one was labelled as GPL by mistake. I'll fixt this ASAP.

**Comment by dgirardeau** [comment]
Ok that's fixed: f46e877ff08d3765e9e114edfccfcb87dff41ac1
