### ISSUE TITLE
A question about computing minPoints and maxPoints in DistanceComputationTools::synchronizeOctrees

### ISSUE THREAD

**Issue by Micalson** [CloudCompare/CCCoreLib#64]
Hello, thank you for the nice code about cloud processing. I have a question, and I am looking forward to your answer. In the function [DistanceComputationTools::synchronizeOctrees](https://github.com/CloudCompare/CCCoreLib/blob/master/src/DistanceComputationTools.cpp#L331), When considering the maxDist variable, I think the minD and maxD should be calculated by the following code.
`minD.u[k] = std::max(minD.u[k], minsA.u[k] - maxDist);
maxD.u[k] = std::min(maxD.u[k], maxsA.u[k] + maxDist);`

Take the intersection of the  compared point cloud enlarged by 'maxDist' and their common boundary boxes as the final boundary boxes.

**Comment by Micalson** [comment]
@dgirardeau Could you help me?

**Comment by dgirardeau** [comment]
Well, it's a bit tricky, but this code has always been like this so I would think it's (still) correct.

The idea is to take the smallest bounding-box between the two clouds, enlarged by 'maxDist'.
- `std::max(minsA.u[k], minsB.u[k])` and `std::min(maxsA.u[k], maxsB.u[k])` return the intersection of the bounding-boxes.
- then we enlarge this intersection bbox by maxDist
- and last we compute the intersection with the previously computed 'addition' bounding-box (minD/maxD)

**Comment by Micalson** [comment]
I get it. Thank you for your explaination.
