### ISSUE TITLE
"GridAndMeshIntersection.h" is missing after installing CCCoreLib

### ISSUE THREAD

**Issue by BirWarrior** [CloudCompare/CCCoreLib#74]
**Describe the bug**
Hey guys thanks for including CCMath.h to the install list. After building again, now "GridAndMeshIntersection.h" is missing in order to use <DistanceComputationTools.h>. Pls include it aswell.

Error: 
In file included from ../main.cpp:10:
/usr/local/include/CCCoreLib/DistanceComputationTools.h:11:10: fatal error: GridAndMeshIntersection.h: No such file or directory
   11 | #include "GridAndMeshIntersection.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**How to reproduce**
see Issue #72 

**Expected behaviour**

**Your environment**
 - CCCoreLib Version (or git hash/tag): https://github.com/CloudCompare/CCCoreLib.git (cloned on monday 09.08.2021)
 - OS & Version: Ubuntu 21.04
 - Qt Version (if compiling w/Qt): 5.15.2

**Comment by BirWarrior** [comment]
I opened the branch `GridAndMeshIntersection--install` and included "GridAndMeshIntersection.h" to the install list. after trying to push it `git push origin GridAndMeshIntersection--install` I got Permission denied. Can someone maybe give me access? @dgirardeau @tmontaigu

**Comment by dgirardeau** [comment]
I believe you just have to push this branch on your personal space (e.g. in a fork of the main repo) and the make the pull request from your (own) branch to our master branch. Otherwise I can fix it on my side if you prefer.
