### ISSUE TITLE
How to create a point cloud pointer?

### ISSUE THREAD

**Issue by whu-lyh** [CloudCompare/CCCoreLib#75]
Hello, thank to your nice code. But i am confused about how initialize a point cloud pointer just like other point cloud libraries, e.g. PCL `pcl::PointCloud<pcl::PointXYZ>::Ptr cloud = boost::make_shared<pcl::PointCloud<pcl::PointXYZ>>()`. And is there a simple tutorial for how implement CCCoreLib to do more interesting job?

**Comment by dgirardeau** [comment]
Well, a PointCloud instance can be created in a very standard way with:
PointCloud* pc = new PointCloud();

But then you'll need to populate it (with reserve, addPoint, etc.).

The best way is to look how it's done in various places of the code: https://github.com/CloudCompare/CCCoreLib/blob/master/src/PointProjectionTools.cpp#L35 (for instance)
