### ISSUE TITLE
CMake Error 

### ISSUE THREAD

**Issue by GaianRan** [CloudCompare/CCCoreLib#88]
**Describe the bug**

when I use CMake tool  to make the CloudCompare&&CCorelib  sourcecode on windows ,it returns the following error:
CMake Error at libs/qCC_db/extern/CCCoreLib/CMakeLists.txt:138 (add_subdirectory):
  add_subdirectory given source "extern/nanoflann" which is not an existing
  directory.
**How to reproduce**

**Expected behaviour**

**Additional context**

CMake Error at libs/qCC_db/extern/CCCoreLib/CMakeLists.txt:138 (add_subdirectory):
  add_subdirectory given source "extern/nanoflann" which is not an existing
  directory.
**Your environment**
 - CCCoreLib Version (or git hash/tag):the latest
 - OS & Version:
 - Qt Version (if compiling w/Qt):5.12.7
 - TBB Version (if compiling w/TBB):

**Comment by dgirardeau** [comment]
Looks like that the nanoflann submodule was not pulled?

Have you used the 'git clone --recurse-submodules' command?

**Comment by GaianRan** [comment]
thank you for your reply , i had download the zip file directly .

**Comment by dgirardeau** [comment]
Ah, that's not the way to do it indeed.
