### ISSUE TITLE
nanoflann.hpp can not compile use vs2015 

### ISSUE THREAD

**Issue by GaianRan** [CloudCompare/CCCoreLib#89]
**Describe the bug**

when i complie CCCoreLib sourcecode with vs2015 ,the file nanoflann.hpp can not  pass , the following line cannot pass:
664         typename std::underlying_type<KDTreeSingleIndexAdaptorFlags>::type;   
  **error C2899: typename cannot be used outside a template declaration**
 i think this error maybe from VC++,so i want to know what is the lowest VC version for this project
**How to reproduce**

**Expected behaviour**

**Additional context**

**Your environment**
 - CCCoreLib Version (or git hash/tag):
 - OS & Version:
 - Qt Version (if compiling w/Qt):
 - TBB Version (if compiling w/TBB):

**Comment by dgirardeau** [comment]
Yep, probably an issue with Visual 2015. You should use 2017 at minimum.
